server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider

  cloud:
    stream:
      binders: # 配置要绑定的rabbitmq的服务信息
        defaultRabbit: #定义的名称，用于binding整合
          type: rabbit #消息组件类型
          environment: #设置rabbitmq的相关环境配置
            spring:
                rabbitmq:
                  host: 192.168.159.138
                  port: 5672
                  username: admin
                  password: 123
      bindings: #服务的整合处理
        output: #信道的名称
          destination: studyExchange #使用的交换机名称
          content-type: application/json #设置消息类型为json，文本text/plain
          binder: defaultRabbit #设置要绑定得消息服务具体设置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳得时间间隔(默认30s)
    lease-expiration-duration-in-seconds: 5 #如果超过了5s时间间隔
    instance-id: send-8801.com #信息列表显示主机名称
    prefer-ip-address: true #访问路径变为ip显示