server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureke的服务名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/monkey1ew/springcloud-config.git #git仓库名字
          # 搜索目录
          search-paths:
            - springcloud-config
      # 读取分支
      label: master

  #rabbitmq配置
  rabbitmq:
    port: 5672
    host: 192.168.159.138
    username: admin
    password: 123

#服务注册进eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka


#rabbitmq相关配置, 暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
