server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率值介于 0-1之间，1-全部采集
        probability: 1

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: fqh

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fqh.springcloud.bean

eureka:
  client:
    # 表示自己是否注册进eurekaServer默认true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的信息，默认为true, 集群必须设置为true才能配置ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      集群
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka/7002.com:7002/eureka #集群
#      单机
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true
#    Eureka客户端向服务提供端发送心跳的时间间隔(默认30s)
    lease-renewal-interval-in-seconds: 1
#    Eureka服务在收到最后一次心跳后等待的时间上限制（默认90s）
    lease-expiration-duration-in-seconds: 2

