server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer

  cloud:
    stream:
      binders: # 配置要绑定的rabbitmq的服务信息
        defaultRabbit: #定义的名称，用于binding整合
          type: rabbit #消息组件类型
          environment: #设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: 192.168.159.138
                port: 5672
                username: admin
                password: 123
      bindings: #服务的整合处理
        input: #信道的名称
          destination: studyExchange #使用的交换机名称
          content-type: application/json #设置消息类型为json，文本text/plain
          binder: defaultRabbit #设置要绑定得消息服务具体设置
#          group: fqhA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳得时间间隔(默认30s)
    lease-expiration-duration-in-seconds: 5 #如果超过了5s时间间隔
    instance-id: recevie-8802.com
    prefer-ip-address: true