server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh           #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**    #断言，路径想匹配的进行路由
        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**
#            - After=2022-04-11T13:42:29.435+08:00[Asia/Shanghai] #在xxx时间之后发送请求
#            - Cookie=username,fqh #请求携带参数
#            - Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性并且为整数的正则

eureka:
  client:
    # 表示自己是否注册进eurekaServer默认true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的信息，默认为true, 集群必须设置为true才能配置ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #      集群
      #      defaultZone: http://eureka7001.com:7001/eureka,http://eureka/7002.com:7002/eureka #集群
      #      单机
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: cloud-gateway-9527